### ISSUE TITLE
Unterstützung für Futro S720 hinzufügen

### ISSUE THREAD

**Issue by oszilloskop** [oszilloskop/Gluon2Futro#3]
Für die Unterstützung von S720 Futros muß die Sicherheitsabfrage der installierten CPU angepasst  werden.

Siehe: https://ffmuc.net/wiki/doku.php?id=knb:s720

**Comment by fschrempf** [comment]
Wurde bereits durch 2aa11dbcb01cb769843acddfebe47cbd46454339 gelöst und funktioniert einwandfrei!

**Comment by oszilloskop** [comment]
Danke für die Rückmeldung.
